# Generated by Django 5.0.7 on 2024-08-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.CharField(max_length=150),
        ),
    ]
