# Generated by Django 5.0.7 on 2024-08-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommersapp', '0002_alter_useraccount_address_alter_useraccount_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='mobileno',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
