# Generated by Django 5.0.7 on 2024-08-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommersapp', '0006_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
