# Generated by Django 5.0.7 on 2024-08-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommersapp', '0007_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
